### ISSUE TITLE
How rank-then-mean is calculated?

### ISSUE THREAD

**Issue by farhanone** [wiesenfa/challengeR#16] opened 2020-02-17 17:59 UTC
Hi,

I am a bit confused about the results when using the **rank-then-mean** scheme.
For 5 algorithms, **rank_FUN** should have values less than or equal to 5 but on the report, the values are far greater than 5.
Right or I am missing something?

Moreover, a small bug in the generated PDF report:
For both ranking schemes(rank-then-aggregate and aggregate-then-rank) the starting description of the report is the same. 

> Ranking of algorithms within tasks according to the following chosen ranking scheme:
> _aggregate using function (“median”) then rank_

For rank-then-aggregate, it should be _rank then aggregate using function (“median”)_

Thanks

**Comment by wiesenfa** [comment] 2020-02-17 22:23
Dear @farhanone,

thanks for pointing out the bug with the rank-then-mean scheme. Should be resolved in the update. Please let me know if you still get something weird. 

your second point I cannot reproduce. When testing I get
"rank then aggregate using function median then rank".
Could you please be more specific about the situation you obtained this?

**Closed** 2020-02-27 20:43 UTC
